from bs4 import BeautifulSoup
import requests
import requests.exceptions
from urllib.parse import urlsplit
from collections import deque
import re
import csv

keywords = ["pre-med Advisor", "pre-health advisor", "health professions advisor", "career advisor", "pre-professional advising stuffs", "pre-med program director", "pre-med program  committee member", "pre-med committee", "pre-med advisory committee member", "pre-health program committee member", "pre-health committee member", "pre-health advisory committee member","premed advisor", "study abroad director", "study abroad", "assistant director", "Global study", "global program", "international program", "chair", "director", "dean", "Biology department faculty", "molecular biology department faculty", "chemistry department faculty", "Education abroad", "health career center", "interim provost", "chancellor for academic affairs", "career center stuff"," global health", "department head", "college of nursing",  "international education", "undergraduate program", "academic affairs", "career professional specialist", "health science", "medical science", "cancer center", "academic counselor", "neuroscience faculty", "life science professor"]
# a queue of urls to be crawled\
'''
'https://www.aic.edu/'
,'https://www.amherst.edu/'
,'https://www.annamaria.edu/'
,'https://www.assumption.edu/'
,'http://www.babson.edu'
,'https://www.baypath.edu/'
,'https://www.baystate.edu/'
,'https://www.becker.edu/'
,'https://www.bentley.edu/'
,'http://www.berkshirecc.edu/'
,'https://www.bc.edu/'
,'https://www.bgsp.edu/'
,'https://www.bc.edu/bc-web/schools/cson.html'
,'https://www.bu.edu/'
,'http://www.bumc.bu.edu/'
,'https://www.brandeis.edu/'
,'https://www.bridgew.edu/'
,'http://www.bristolcc.edu/'
,'https://www.bhcc.edu/'
,'https://www.cambridgecollege.edu/'
,'https://www.capecod.edu/'
,'https://www.capecod.edu/'
,'https://www.holycross.edu/'
,'https://www.curry.e'
,'https://www.dean.edu/'
,'https://enc.edu/'
,'https://www.elms.edu/'
,'https://www.elms.edu/'
,'https://www.elms.edu/school-of-nursing/'
,'https://www.emmanuel.edu/'
,'https://www.endicott.edu/'
,'http://www.fisher.edu/'
,'https://online.fitchburgstate.edu'
,'https://www.framingham.edu/'
,'https://my.gordon.edu'
,'http://www.gordonconwell.edu'
,'http://www.gcc.mass.edu/'
,'https://www.hampshire.edu/'
,'https://www.harvard.edu/'
,'http://www.hebrewcollege.edu/'
,'https://www.hcc.edu/'
,'https://lesley.edu/'
,'https://www.massbay.edu/'
,'http://www.mcla.edu/'
,'http://www.mit.edu/'
,'https://www.massasoit.edu'
,'https://www.mcphs.edu/'
,'https://www.merrimack.edu/'
,'https://www.mghihp.edu/'
,'https://www.middlesex.mass.edu/'
,'https://www.mtholyoke.edu/'
,'https://mwcc.edu/'
,'https://www.neco.edu/'
,'https://newbury.edu/'
,'https://www.nichols.edu/'
,'http://www.northshore.edu/'
,'https://www.northeastern.edu/'
,'https://www.necc.mass.edu/'
,'http://www.pmc.edu/'
,'http://www.psjs.edu/'
,'https://quincycollege.edu/'
,'https://www.qcc.edu/'
,'http://www.regiscollege.edu/'
,'http://www.regiscollege.edu/academics/school-of-nursing.cfm'
,'http://www.rcc.mass.edu/'
,'https://www.salemstate.edu/'
,'http://www.simmons.edu/'
,'https://www.smith.edu/'
,'https://springfield.edu/'
,'https://www.stcc.edu'
,'https://www.stonehill.edu/'
,'https://www.suffolk.edu/'
,'https://www.tufts.edu/'
,'https://www.umass.edu/'
,'https://www.umb.edu/'
,'https://www.umassd.edu/'
,'https://www.uml.edu/'
,'https://www.umassmed.edu/'
,'http://www.urbancollege.edu/'
,'http://www.wellesley.edu/'
,'https://wit.edu'
,'https://www1.wne.edu/'
,'http://www.westfield.ma.edu/'
,'https://www.wheaton.edu/'
,'http://www.bu.edu/wheelock/'
,'https://www.williamjames.edu/'
,'https://www.williams.edu/'
,'https://www.wpi.edu/'
,'https://www.worcester.edu/'
,'https://www.aiuniv.edu/'
,'http://www.aicusa.edu/'
,'https://www.argosy.edu/'
,'https://www.augustana.edu/'
,'https://aurora.edu/'
,'https://blackburn.edu/'
,'http://www.ben.edu/'
,'https://www.bradley.edu/'
,'http://www.lakeforest.edu'
,'https://www.lakeviewcol.edu/'
,'https://go.chamberlain.edu'
,'https://www.csu.edu/'
,'https://www.colum.edu/'
,'https://www.cuchicago.edu/'
,'https://www.coynecollege.edu/'
,'https://www.depaul.edu'
,'https://www.devry.edu/'
,'https://www.dom.edu/'
,'https://eiupanthers.com/'
,'https://www.eastwest.edu/'
,'https://www.elmhurst.edu/'
,'https://www.erikson.edu/'
,'https://www.eureka.edu/'
,'https://www.foxcollege.edu'
,'http://www.govst.edu/'
,'https://www.greenville.edu/'
,'https://www.ic.edu/'
,'https://web.iit.edu/'
,'https://go.argosy.edu'
,'https://illinoisstate.edu/'
,'https://www.iwu.edu/'
,'http://www.judsonu.edu/'
,'https://www.kendall.edu/'
,'https://www.knox.edu/'
,'https://www.lewisu.edu/'
,'https://lincolnchristian.edu/'
,'https://lincolncollege.edu/'
,'http://www.lindenwood.edu'
,'https://www.luc.edu/'
,'https://www.lstc.edu/'
,'https://www.maccormac.edu/'
,'https://www.mac.edu/'
,'https://www.mckendree.edu/'
,'https://www.midstate.edu/'
,'http://www.acupuncture.edu/'
,'https://www.midwesttech.edu/'
,'https://www.midwestern.edu'
,'https://millikin.edu/'
,'https://ou.monmouthcollege.edu'
,'https://www.nl.edu/'
,'https://www.nuhs.edu/'
,'https://info.ncu.edu'
,'https://www.northpark.edu/'
,'https://www.neiu.edu/'
,'https://onlinenursing.northeastern.edu'
,'https://www.ats.edu'
,'https://www.niu.edu'
,'https://www.nwciowa.edu/'
,'https://www.northwestern.edu/'
,'https://www.olivet.edu/'
,'https://www.pacificcollege.edu/'
,'http://www.principiacollege.edu/'
,'https://www.quincy.edu/'
,'https://www.rasmussen.edu/'
,'https://www.rmu.edu/'
,'https://robertmorris.edu/'
,'https://www.rockfordcareercollege.edu/'
,'https://www.rockford.edu/'
,'https://www.roosevelt.edu/'
,'https://www.rosalindfranklin.edu/'
,'https://www.rosalindfranklin.edu/academics/chicago-medical-school/'
,'https://www.rushu.rush.edu'
,'https://www.osfhealthcare.org/sacn/'
,'https://www.sxu.edu/'
,'https://siu.edu/'
,'https://www.spertus.edu/'
,'https://achieve.strayer.edu'
,'https://www.thechicagoschool.edu'
,'https://www.trnty.edu/'
,'https://www.tiu.edu/'
,'https://www.uchicago.edu/'
,'https://www.uic.edu/'
,'https://www.uis.edu/'
,'https://illinois.edu/'
,'https://www.uillinois.edu/'
,'https://www.sf.edu/'
,'http://www.vatterott.edu/'
,'http://www.wiu.edu/'
,'http://www.westwood.edu/'
,'https://www.wheaton.edu/'
,'https://realize.brightwood.edu'
,'http://www.ccnn.edu/'
,'https://www.csn.edu/'
,'https://www.dri.edu/'
,'https://get-started.devry.edu'
,'http://www.gbcnv.edu/'
,'https://www.nu.edu/'
,'https://nsc.edu/'
,'https://www.northwestcareercollege.edu/'
,'https://pmi.edu/'
,'http://www.roseman.edu/'
,'https://www.sierranevada.edu/'
,'https://tun.touro.edu/'
,'http://www.tmcc.edu/'
,'https://www.unlv.edu/'
,'https://www.unr.edu/'
,'https://www.phoenix.edu'
,'https://www.wnc.edu/'
,'http://wonguuniversity.com/'
,'https://wongu.org/'
,'https://info.alliant.edu'
'''
new_urls = deque([
'https://ahusc.net/'
,'https://www.aju.edu/'
,'https://www.anaheim.edu/'
,'https://www.antioch.edu/los-angeles/'
,'https://go.argosy.edu/'
,'https://www.argosy.edu'
,'https://www.argosy.edu/locations/los-angeles-orange-county'
,'https://www.argosy.edu/locations/san-diego'
,'https://www.argosy.edu/locations/san-francisco'
,'https://www.biola.edu/'
,'https://www.brandman.edu/'
,'https://lasierra.edu'
,'https://calbaptist.edu'
,'https://www.cc-sd.edu/'
,'https://www.ciis.edu/'
,'http://www.caltech.edu/'
,'https://www.callutheran.edu/'
,'https://www.calmu.edu'
,'https://www.calpoly.edu/'
,'https://www.calsouthern.edu/'
,'https://www.cpp.edu/'
,'http://www.csub.edu/'
,'https://www.csuci.edu/'
,'http://www.csuchico.edu/'
,'https://www.csudh.edu/'
,'https://www.csueastbay.edu/'
,'http://www.csufresno.edu/'
,'http://www.fullerton.edu/'
,'http://www.csulb.edu/'
,'http://www.calstatela.edu'
,'https://csumb.edu/'
,'https://www.csun.edu/'
,'https://www.csus.edu/'
,'https://www.csusb.edu/'
,'https://www.csusm.edu/'
,'https://www.csustan.edu/'
,'https://www2.calstate.edu'
,'http://www.calums.edu'
,'https://www.cgu.edu'
,'https://www.cmc.edu/'
,'https://www.chapman.edu/'
,'https://www.cdrewu.edu/'
,'https://cogswell.edu'
,'https://www.cui.edu'
,'https://www.ciachef.edu/cia-california/'
,'https://www.deepsprings.edu/'
,'https://www.devry.edu'
,'https://home.dominican.edu/'
,'https://www.emperors.edu/'
,'https://www.fresno.edu/'
,'https://www.fuller.edu/'
,'http://www.ggu.edu/'
,'https://www.gtu.edu/'
,'https://www.hmc.edu/'
,'http://www.herguanuniversity.edu/'
,'https://dentistry.usc.edu/'
,'https://www.hnu.edu/'
,'https://www.hiu.edu/'
,'https://www.humboldt.edu/'
,'https://www.humphreys.edu/'
,'https://itu.edu/'
,'https://www.jfku.edu/'
,'https://jpcatholic.edu/'
,'https://www.kgi.edu/'
,'https://keck.usc.edu/'
,'http://www.lifepacific.edu/'
,'http://www.lincoln.edu/'
,'https://medicine.llu.edu/'
,'https://home.llu.edu/'
,'https://dentistry.llu.edu/'
,'https://www.lmu.edu/'
,'https://www.marymountcalifornia.edu/'
,'http://www.menlo.edu/'
,'https://www.middlebury.edu'
,'https://www.mills.edu/'
,'http://www.msmary.edu/'
,'https://www.nu.edu/'
,'https://www.ndnu.edu/'
,'http://oakvalleycollege.org/'
,'https://www.oxy.edu/'
,'https://www.otis.edu/'
,'https://www.plts.edu/'
,'https://www.pacificoaks.edu/'
,'https://www.puc.edu'
,'https://www.pacifica.edu/'
,'http://www.palmer.edu'
,'https://www.paloaltou.edu/'
,'https://www.prgs.edu/'
,'http://staging.patten.edu/'
,'https://www.pepperdine.edu/'
,'https://www.pitzer.edu/'
,'https://www.pointloma.edu/'
,'https://www.pomona.edu/'
,'http://www.seabeggars.com/'
,'https://www.stmarys-ca.edu/'
,'https://www.samuelmerritt.edu/'
,'https://www.samuelmerritt.edu/nursing'
,'https://www.samuelmerritt.edu/physician_assistant'
,'https://sdcc.edu/'
,'https://www.sdsu.edu/'
,'https://sduis.edu'
,'http://www.sfsu.edu/'
,'http://www.sjsu.edu/'
,'https://www.scu.edu/'
,'https://www.saybrook.edu/'
,'http://www.scrippscollege.edu/'
,'https://simpsonu.edu/'
,'http://www.soka.edu/'
,'https://www.sonoma.edu/'
,'https://www.ssu.edu/'
,'Stanford University'
,'https://thomasaquinas.edu/'
,'http://www.tu.edu/'
,'https://go.trident.edu/'
,'https://medschool.ucla.edu/'
,'https://www.dentistry.ucla.edu/'
,'http://www.som.uci.edu/'
,'https://medschool.ucr.edu/'
,'https://medschool.ucsd.edu'
,'https://laverne.edu/'
,'https://www.berkeley.edu/'
,'https://www.ucdavis.edu/'
,'https://uci.edu/'
,'http://www.ucla.edu/'
,'https://www.ucmerced.edu/'
,'https://www.ucr.edu/'
,'https://ucsd.edu/'
,'https://www.ucsf.edu/'
,'https://www.ucsb.edu/'
,'https://www.ucsc.edu/'
,'https://www.uncm.edu/'
,'http://www.redlands.edu/'
,'http://www.sandiego.edu/'
,'https://www.usfca.edu/'
,'https://www.usc.edu/'
,'https://www.pacific.edu/'
,'https://www.uopeople.edu/'
,'https://www.uwest.edu/'
,'https://www.uwla.edu/'
,'https://www.vanguard.edu'
,'https://www.westernu.edu/'
,'https://www.westmont.edu/'
,'https://www.whittier.edu/'
,'https://woodbury.edu/'
,'http://www.acu.edu/'
,'https://www.ttuhsc.edu'
,'https://www.amberton.edu'
,'Angelo State University'
,'https://www.abu.edu/'
,'https://www.austincollege.edu/'
,'https://www.austincollege.edu/'
,'https://dentistry.tamhsc.edu'
,'https://www.baylor.edu/'
,'https://www.baylor.edu/'
,'https://www.chcp.edu/'
,'https://thomasmorecollege.edu/'
,'https://www.concordia.edu/'
,'https://www.covenanthealth.org'
,'http://www.criswell.edu/'
,'https://www.dbu.edu'
,'https://www.dallas.edu/'
,'https://www.etbu.edu/'
,'https://www.umassmed.edu'
,'https://hallmarkuniversity.edu'
,'https://www.hsutx.edu/'
,'https://www.hbu.edu'
,'http://www.hputx.edu/'
,'https://ibt.tamhsc.edu/'
,'https://degree.lamar.edu'
,'https://www.letu.edu/'
,'https://lcu.edu/'
,'https://ww2.mcm.edu/'
,'https://mwsu.edu/'
,'https://academicpartnerships.uta.edu'
,'http://www.na.edu/'
,'https://www.northwood.edu/'
,'http://www.ollusa.edu'
,'https://www.parker.edu/'
,'http://www.pqc.edu/'
,'https://www.pvamu.edu/'
,'http://landing.online.queens.edu'
,'https://www.rice.edu/'
,'http://www.shsu.edu/'
,'https://degrees.schreiner.edu'
,'https://www.smu.edu/'
,'https://www.swau.edu/'
,'http://www.swcc.edu/'
,'https://www.southwestern.edu/'
,'https://pages.stedwards.edu'
,'https://www.stmarytx.edu/'
,'http://www.sfasu.edu/'
,'https://www.sulross.edu/'
,'https://www.tarleton.edu/home/'
,'https://cbhec.tamhsc.edu/'
,'https://medicine.tamhsc.edu/'
,'http://vetmed.tamu.edu'
,'https://pharmacy.tamhsc.edu/'
,'https://sph.tamhsc.edu/'
,'https://healthytexas.tamu.edu/'
,'https://online.tamiu.edu'
,'https://www.tamu.edu/'
,'https://www.tamhsc.edu/'
,'https://www.tamuct.edu/'
,'https://www.tamuc.edu/'
,'https://www.tamucc.edu/'
,'http://www.tamuk.edu/'
,'http://www.tamusa.edu/'
,'http://tamut.edu/'
,'http://www.txchiro.edu/'
,'http://www.tcu.edu/'
,'https://www.texascollege.edu/'
,'https://www.unthsc.edu/texas-college-of-osteopathic-medicine/'
,'http://www.tlu.edu/'
,'http://www.tsu.edu'
,'http://www.txstate.edu/'
,'https://www.ttu.edu/'
,'https://www.ttuhsc.edu/'
,'http://elpaso.ttuhsc.edu/'
,'https://txwes.edu/'
,'https://twu.edu/'
,'https://new.trinity.edu/'
,'https://udallas.edu/'
,'http://www.uh.edu/'
,'https://www.uh.edu/pharmacy/'
,'https://www.uhcl.edu/'
,'https://www.uhd.edu/'
,'https://www.uhv.edu/'
,'https://go.umhb.edu/'
,'https://www.unt.edu/'
,'https://www.untdallas.edu/'
,'https://www.unthsc.edu/'
,'https://www.stthomas.edu/'
,'https://www.utexas.edu/'
,'https://dellmed.utexas.edu/'
,'https://www.utdallas.edu/'
,'https://www.utep.edu/'
,'https://www.utsa.edu/'
,'http://www.uttyler.edu/'
,'https://www.uth.edu/'
,'http://www.uthscsa.edu/'
,'https://www.utsystem.edu'
,'https://www.utpb.edu/'
,'https://www.utrgv.edu/en-us/'
,'https://www.utsouthwestern.edu/'
,'http://www.uiw.edu/'
,'http://www.uiw.edu/som/'
,'http://www.wtamu.edu/'
,'https://texas.wgu.edu/'
,'http://www.wtc.edu'
,'https://www.wileyc.edu/'

])
counter = 0
linecounter = 0

# a set of urls that we have already crawled
processed_urls = set()

# a set of crawled emails
emails = set()

# process urls one by one until we exhaust the queue
while len(new_urls):
    
    counter += 1
    # move next url from the queue to the set of processed urls
    url = new_urls.popleft()
    processed_urls.add(url)

    # extract base url to resolve relative links
    parts = urlsplit(url)
    base_url = "{0.scheme}://{0.netloc}".format(parts)
    path = url[:url.rfind('/')+1] if '/' in parts.path else url

    # get url's content
    # print("Processing %s" % url)
    # if len(url) < 45:
    #     print("new url " + url)
    # else:
    #     print("new url " + url[0:50])
    # # print("new url" + url)

    # if (linecounter >= 5000):
    #     print("reached 5000 lines")
    #     print("url")
    #     break
    linecounter += 1
    print(linecounter)
    try:
        response = requests.get(url)
    except (requests.exceptions.InvalidSchema,requests.exceptions.MissingSchema, requests.exceptions.ConnectionError, requests.exceptions.InvalidURL,requests.exceptions.TooManyRedirects, AttributeError):
        # ignore pages with errors
        continue
    for key in keywords:
        if key in response.text:
            print("adding email")
            # extract all email addresses and add them into the resulting set
            new_emails = set(re.findall(r"[a-z0-9\.\-+_]+@[a-z0-9\.\-+_]+\.[a-z]+", response.text, re.I))
            emails.update(new_emails)
            break
        


    if counter >= 10:
        print("writing csv -------------------------\n")
        with open("./sepList3.txt", 'a') as f:
            for x in emails:
                print(x)
                f.write(x + "\n")
        # writer = csv.writer(open("./emails.csv", 'w'))

        # for x in emails:
        #     writer.writerow(x)
        counter = 0

        print("finished writing--------------------\n")


    # create a beutiful soup for the html document
    soup = BeautifulSoup(response.text,features="lxml")

    # find and process all the anchors in the document
    for anchor in soup.find_all("a"):
        # extract link url from the anchor
        link = anchor.attrs["href"] if "href" in anchor.attrs else ''
        if ".edu" in link:
            # resolve relative links
            if link.startswith('/'):
                link = base_url + link
            elif not link.startswith('http'):
                link = path + link
            # add the new url to the queue if it was not enqueued nor processed yet
            if not link in new_urls and not link in processed_urls:
                new_urls.append(link)
            


print("the end")
